Fix AuthGuard and CompleteProfileModal errors
Fixes the following errors:
- src/components/auth/AuthGuard.tsx(28,8): error TS2741: Property 'open' is missing in type '{}' but required in type 'CompleteProfileModalProps'.
- src/components/auth/CompleteProfileModal.tsx(60,51): error TS2322: Type '{ children: Element[]; className: string; hideCloseButton: true; }' is not assignable to type 'IntrinsicAttributes & Omit<DialogContentProps & RefAttributes<HTMLDivElement>, "ref"> & RefAttributes<...>'.